#include "stm32f4xx.h"
#include "adc.h"

void ADC_Init() {
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
	RCC->APB2ENR |= RCC_APB2ENR_ADC1EN;

	GPIOA->MODER |= GPIO_MODER_MODE0_0 | GPIO_MODER_MODE0_1;
		
	ADC1->SMPR2 = ADC_SMPR2_SMP0_0;
	ADC1->SQR1 = ADC_SQR1_L_0;
	ADC1->SQR3 = 0;
	ADC1->CR2 |= ADC_CR2_ADON;
}

uint32_t ADC_Read_Channel_0() {
	ADC1->CR2 |= ADC_CR2_SWSTART;
	while(!(ADC1->SR & ADC_SR_EOC));
	return ADC1->DR;
}
